import type { Metadata } from "next";
import React from "react";
import { FaPhoneAlt, FaEnvelope } from "react-icons/fa";

export const metadata: Metadata = {
  title: "Privacy Policy | Gokul Agro Tourism",
  description:
    "Read the Privacy Policy for Gokul Agro Tourism to understand how we collect, use, and protect your personal information.",
  robots: {
    index: false,
    follow: true,
  },
  openGraph: {
    title: "Privacy Policy | Gokul Agro Tourism",
    description:
      "Read the Privacy Policy for Gokul Agro Tourism to understand how we collect, use, and protect your personal information.",
    url: "https://www.gokulagrotourism.com/privacy-policy",
    type: "website",
    locale: "en_IN",
    siteName: "Gokul Agro Tourism",
  },
};

const PrivacyPolicyPage = () => {
  return (
    <main className="bg-white px-4 py-12 md:px-8 lg:px-12">
      <div className="mx-auto max-w-4xl rounded-2xl border border-gray-200 bg-white p-6 shadow-sm md:p-10">
        <div className="mb-10 border-b border-gray-200 pb-6">
          <h1 className="text-3xl font-bold text-center tracking-tight text-gray-900 md:text-4xl">
            Privacy Policy
          </h1>
          <p className="mt-3 text-sm text-gray-500">
            Last updated: April 03, 2024
          </p>
          <p className="mt-4 text-base leading-7 text-gray-700">
            This Privacy Policy describes our policies and procedures on the
            collection, use, and disclosure of your information when you use our
            service and explains your privacy rights and how the law protects
            you.
          </p>
          <p className="mt-4 text-base leading-7 text-gray-700">
            We use your personal data to provide and improve our service. By
            using the service, you agree to the collection and use of
            information in accordance with this Privacy Policy.
          </p>
        </div>

        <section className="space-y-8 text-gray-700">
          <div>
            <h2 className="text-2xl font-semibold text-gray-900">
              Interpretation and Definitions
            </h2>
            <h3 className="mt-4 text-lg font-semibold text-gray-900">
              Interpretation
            </h3>
            <p className="mt-2 leading-7">
              Words with capitalized initials have meanings defined under the
              following conditions. These definitions apply whether they appear
              in singular or plural.
            </p>

            <h3 className="mt-6 text-lg font-semibold text-gray-900">
              Definitions
            </h3>
            <p className="mt-2 leading-7">
              For the purposes of this Privacy Policy:
            </p>

            <ul className="mt-4 list-disc space-y-3 pl-6">
              <li>
                <strong>Account</strong> means a unique account created for you
                to access our service or parts of our service.
              </li>
              <li>
                <strong>Affiliate</strong> means an entity that controls, is
                controlled by, or is under common control with a party, where
                “control” means ownership of 50% or more of the shares, equity
                interest, or other securities entitled to vote for election of
                directors or other managing authority.
              </li>
              <li>
                <strong>Company</strong> (referred to as “the Company”, “We”,
                “Us”, or “Our” in this Policy) refers to Gokul Agro Tourism.
              </li>
              <li>
                <strong>Cookies</strong> are small files placed on your
                computer, mobile device, or any other device by a website,
                containing details of your browsing history on that website.
              </li>
              <li>
                <strong>Country</strong> refers to Maharashtra, India.
              </li>
              <li>
                <strong>Device</strong> means any device that can access the
                service such as a computer, cellphone, or digital tablet.
              </li>
              <li>
                <strong>Personal Data</strong> is any information that relates
                to an identified or identifiable individual.
              </li>
              <li>
                <strong>Service</strong> refers to the website.
              </li>
              <li>
                <strong>Service Provider</strong> means any natural or legal
                person who processes data on behalf of the Company.
              </li>
              <li>
                <strong>Third-party Social Media Service</strong> refers to any
                website or social network through which a user can log in or
                create an account to use the service.
              </li>
              <li>
                <strong>Usage Data</strong> refers to data collected
                automatically, either generated by the use of the service or
                from the service infrastructure itself.
              </li>
              <li>
                <strong>Website</strong> refers to Gokul Agro Tourism,
                accessible at{" "}
                <a
                  href="https://www.gokulagrotourism.com/"
                  target="_blank"
                  rel="noopener noreferrer nofollow"
                  className="text-orange-600 underline underline-offset-4 hover:text-orange-500"
                >
                  www.gokulagrotourism.com
                </a>
                .
              </li>
              <li>
                <strong>You</strong> means the individual accessing or using the
                service, or the company or other legal entity on behalf of which
                such individual is accessing or using the service.
              </li>
            </ul>
          </div>

          <div>
            <h2 className="text-2xl font-semibold text-gray-900">
              Collecting and Using Your Personal Data
            </h2>

            <h3 className="mt-6 text-lg font-semibold text-gray-900">
              Types of Data Collected
            </h3>

            <h4 className="mt-4 text-base font-semibold text-gray-900">
              Personal Data
            </h4>
            <p className="mt-2 leading-7">
              While using our service, we may ask you to provide certain
              personally identifiable information that can be used to contact or
              identify you. This may include:
            </p>
            <ul className="mt-3 list-disc space-y-2 pl-6">
              <li>First name and last name</li>
              <li>Phone number</li>
              <li>Usage Data</li>
            </ul>

            <h4 className="mt-6 text-base font-semibold text-gray-900">
              Usage Data
            </h4>
            <p className="mt-2 leading-7">
              Usage Data is collected automatically when using the service. It
              may include information such as your IP address, browser type,
              browser version, visited pages, visit time and date, time spent on
              pages, device identifiers, and other diagnostic data.
            </p>
            <p className="mt-2 leading-7">
              When you access the service through a mobile device, we may
              collect information such as the type of mobile device you use,
              mobile device unique ID, mobile IP address, operating system,
              mobile browser type, and other diagnostic data.
            </p>

            <h4 className="mt-6 text-base font-semibold text-gray-900">
              Tracking Technologies and Cookies
            </h4>
            <p className="mt-2 leading-7">
              We use cookies and similar tracking technologies to track activity
              on our service and store certain information. These may include
              cookies, web beacons, tags, and scripts used to improve and
              analyze the service.
            </p>
            <ul className="mt-3 list-disc space-y-3 pl-6">
              <li>
                <strong>Necessary / Essential Cookies:</strong> Required to
                provide core website functionality.
              </li>
              <li>
                <strong>Cookies Acceptance Cookies:</strong> Used to remember
                whether users have accepted cookies.
              </li>
              <li>
                <strong>Functionality Cookies:</strong> Used to remember your
                preferences and provide a better user experience.
              </li>
            </ul>
          </div>

          <div>
            <h3 className="text-lg font-semibold text-gray-900">
              Use of Your Personal Data
            </h3>
            <p className="mt-2 leading-7">
              The Company may use personal data for the following purposes:
            </p>
            <ul className="mt-3 list-disc space-y-3 pl-6">
              <li>To provide and maintain our service.</li>
              <li>To manage your account and registration.</li>
              <li>To perform contracts for services or bookings.</li>
              <li>To contact you by phone, SMS, or email when necessary.</li>
              <li>
                To provide updates, offers, and relevant service information.
              </li>
              <li>To manage your requests and inquiries.</li>
              <li>To improve our website, services, and user experience.</li>
            </ul>
          </div>

          <div>
            <h3 className="text-lg font-semibold text-gray-900">
              Sharing of Your Personal Data
            </h3>
            <p className="mt-2 leading-7">
              We may share your personal information in the following
              situations:
            </p>
            <ul className="mt-3 list-disc space-y-3 pl-6">
              <li>With service providers who help operate our service.</li>
              <li>
                During business transfers such as mergers or acquisitions.
              </li>
              <li>With affiliates and business partners where necessary.</li>
              <li>With your consent for any other disclosed purpose.</li>
            </ul>
          </div>

          <div>
            <h3 className="text-lg font-semibold text-gray-900">
              Retention of Your Personal Data
            </h3>
            <p className="mt-2 leading-7">
              We retain your personal data only for as long as necessary for the
              purposes set out in this Privacy Policy, including compliance with
              legal obligations, dispute resolution, and enforcement of
              agreements.
            </p>
          </div>

          <div>
            <h3 className="text-lg font-semibold text-gray-900">
              Transfer of Your Personal Data
            </h3>
            <p className="mt-2 leading-7">
              Your information may be processed at the Company’s operating
              offices and in other places where parties involved in the
              processing are located. This means your data may be transferred to
              and maintained on computers located outside your state or country,
              where data protection laws may differ.
            </p>
          </div>

          <div>
            <h3 className="text-lg font-semibold text-gray-900">
              Delete Your Personal Data
            </h3>
            <p className="mt-2 leading-7">
              You have the right to request deletion of the personal data we
              have collected about you. You may also contact us to access,
              correct, or delete your personal information.
            </p>
          </div>

          <div>
            <h3 className="text-lg font-semibold text-gray-900">
              Disclosure of Your Personal Data
            </h3>
            <ul className="mt-3 list-disc space-y-3 pl-6">
              <li>To comply with legal obligations.</li>
              <li>
                To protect and defend the rights or property of the Company.
              </li>
              <li>
                To investigate possible wrongdoing related to the service.
              </li>
              <li>To protect the safety of users or the public.</li>
              <li>To protect against legal liability.</li>
            </ul>
          </div>

          <div>
            <h3 className="text-lg font-semibold text-gray-900">
              Security of Your Personal Data
            </h3>
            <p className="mt-2 leading-7">
              The security of your personal data is important to us, but no
              method of transmission over the internet or electronic storage is
              completely secure. While we strive to use commercially acceptable
              means to protect your personal data, we cannot guarantee its
              absolute security.
            </p>
          </div>

          <div>
            <h2 className="text-2xl font-semibold text-gray-900">
              Children’s Privacy
            </h2>
            <p className="mt-2 leading-7">
              Our service does not address anyone under the age of 13. We do not
              knowingly collect personally identifiable information from
              children under 13.
            </p>
          </div>

          <div>
            <h2 className="text-2xl font-semibold text-gray-900">
              Links to Other Websites
            </h2>
            <p className="mt-2 leading-7">
              Our service may contain links to third-party websites that are not
              operated by us. We strongly advise you to review the privacy
              policy of every site you visit.
            </p>
          </div>

          <div>
            <h2 className="text-2xl font-semibold text-gray-900">
              Changes to this Privacy Policy
            </h2>
            <p className="mt-2 leading-7">
              We may update this Privacy Policy from time to time. Any changes
              will be posted on this page along with an updated revision date.
            </p>
          </div>

          <div>
            <h2 className="text-2xl font-semibold text-gray-900">Contact Us</h2>
            <p className="mt-2 leading-7 ">
              If you have any questions about this Privacy Policy, you can
              contact us at:
            </p>
            <div className="space-y-3">
              <a
                href="tel:+919423121863"
                className="flex items-center gap-3 text-sm sm:text-base text-gray-600 hover:text-orange-500 transition-colors duration-300"
              >
                <FaPhoneAlt className="text-orange-400" />
                <span>+91 9423121863</span>
              </a>

              <a
                href="mailto:gokulagrotourism@gmail.com"
                className="flex items-center gap-3 text-sm sm:text-base text-gray-600 hover:text-orange-500 transition-colors duration-300"
              >
                <FaEnvelope className="text-orange-400" />
                <span>gokulagrotourism@gmail.com</span>
              </a>
            </div>
          </div>
        </section>
      </div>
    </main>
  );
};

export default PrivacyPolicyPage;